export const AUTH_ACTIONS = {
    AUTHENTICATE_USER: "AUTHENTICATE_USER",
    FETCH_AUTHORIZED_USER: "FETCH_AUTHORIZED_USER",
    SIGN_OUT: "SIGN_OUT"
}

export const USER_ACTIONS = {
    SIGN_UP_USER: "SIGN_UP_USER",
    GET_USER_LIST: "GET_USER_LIST"
}

export const CREDIT_INFO_ACTIONS = {
    GET_USER_CREDIT_INFO: "GET_USER_CREDIT_INFO"
}

export const CATEGORY_ACTIONS = {
    GET_CATEGORIES: "GET_CATEGORIES",
    GET_CATEGORY: "GET_CATEGORY",
    CREATE_CATEGORY: "CREATE_CATEGORY",
    UPDATE_CATEGORY: "UPDATE_CATEGORY",
}

export const COMMON_ACTIONS = {
    REQUEST: '_REQUEST',
    SUCCESS: '_SUCCESS',
    ERROR: '_ERROR',
    CLEAR: '_CLEAR'
}