export const AUTH_ACTIONS = {
    AUTHENTICATE_USER: "AUTHENTICATE_USER",
    FETCH_AUTHORIZED_USER: "FETCH_AUTHORIZED_USER",
    SIGN_OUT: "SIGN_OUT"
}

export const CREDIT_INFO_ACTIONS = {
    GET_USER_CREDIT_INFO: "GET_USER_CREDIT_INFO"
}

export const COMMON_ACTIONS = {
    REQUEST: '_REQUEST',
    SUCCESS: '_SUCCESS',
    ERROR: '_ERROR',
    CLEAR: '_CLEAR'
}